# Generated by fleetix; do not edit by hand.
{
  harnesses = {
    opencode = {
      __pkl_class = "Harness";
      format = "json";
      path = "$XDG_CONFIG_HOME/opencode/opencode.json";
      root = [
        "mcp"
        "servers"
      ];
      commands = [
        "opencode"
      ];
    };
    codex = {
      __pkl_class = "Harness";
      format = "toml";
      path = "$HOME/.codex/config.toml";
      root = [
        "mcp_servers"
      ];
      commands = [
        "codex"
      ];
    };
    claude = {
      __pkl_class = "Harness";
      format = "json";
      path = "$HOME/.claude.json";
      root = [
        "mcpServers"
      ];
      commands = [
        "claude"
      ];
    };
    omp = {
      __pkl_class = "Harness";
      format = "json";
      path = "$HOME/.omp/agent/mcp.json";
      root = [
        "mcpServers"
      ];
      commands = [
        "omp"
      ];
    };
    gemini = {
      __pkl_class = "Harness";
      format = "json";
      path = "$HOME/.gemini/settings.json";
      root = [
        "mcpServers"
      ];
      commands = [
        "gemini"
      ];
    };
    kiro = {
      __pkl_class = "Harness";
      format = "json";
      path = "$HOME/.kiro/settings/mcp.json";
      root = [
        "mcpServers"
      ];
      commands = [
        "kiro-cli"
      ];
    };
    copilot = {
      __pkl_class = "Harness";
      format = "json";
      path = "$HOME/.copilot/mcp-config.json";
      root = [
        "mcpServers"
      ];
      commands = [
        "copilot"
      ];
    };
    zed = {
      __pkl_class = "Harness";
      format = "json";
      path = "$XDG_CONFIG_HOME/zed/settings.json";
      root = [
        "context_servers"
      ];
      commands = [
        "zeditor"
        "zed"
      ];
    };
    hermes = {
      __pkl_class = "Harness";
      format = "native";
      path = "";
      root = [
        "mcp_servers"
      ];
      commands = [
        "hermes"
      ];
    };
  };
}
