{ lib }:
let
  inherit (builtins) attrNames hasAttr;
  inherit (lib)
    filter
    filterAttrs
    findFirst
    hasSuffix
    mapAttrs
    mapAttrsToList
    optionalAttrs
    recursiveUpdate
    splitString
    ;

  linkAddress = host: linkName:
    (host.links.${linkName}.address or null);

  hostAddressByKind = host: kind:
    if kind == "lan" then
      host.network.lanIp or null
    else if kind == "direct-link" then
      let
        directLinkIp = host.network.directLinkIp or null;
      in
      if directLinkIp != null then directLinkIp else linkAddress host "direct-link"
    else
      linkAddress host kind;

  firstNonNull = values:
    findFirst (value: value != null) null values;

  requireValue = message: value:
    if value == null then throw message else value;

  lookupHost = topology: hostName:
    topology.hosts.${hostName} or null;

  lookupReverseProxyService = topology: serviceName:
    findFirst (svc: svc.name == serviceName) null (topology.services.reverseProxyServices or []);

  resolveHostAddressImpl = {
    topology,
    hostName,
    policy,
    require ? true,
  }:
    let
      host = lookupHost topology hostName;
      address =
        if host == null then
          null
        else
          firstNonNull (map (kind: hostAddressByKind host kind) policy);
    in
      if require then
        requireValue
          "fleetix.resolveHostAddress: host `${hostName}` has no address for policy [${toString policy}]"
          address
      else
        address;
in
rec {
  # Import a fleetix topology sidecar (.nix file generated by pklx eval).
  fromPkl = builtins.import;

  hosts = {
    resolveHostAddress = resolveHostAddressImpl;
  };

  services = {
    reverseProxyServicesForHost = {
      topology,
      hostName,
      includeVpnOnly ? false,
    }:
      filter (
        svc:
          (svc.targetHost or null) == hostName
          && (includeVpnOnly || !(svc.vpnOnly or false))
      ) (topology.services.reverseProxyServices or []);

    serviceEndpoint = {
      topology,
      serviceName,
      addressPolicy,
      scheme ? null,
      require ? true,
    }:
      let
        svc = lookupReverseProxyService topology serviceName;
        targetHost =
          if svc == null then
            null
          else
            svc.targetHost or null;
        address =
          if svc == null || targetHost == null then
            null
          else
            hosts.resolveHostAddress {
              inherit topology require;
              hostName = targetHost;
              policy = addressPolicy;
            };
        endpoint =
          if svc == null || targetHost == null || address == null then
            null
          else
            let
              endpointScheme =
                if scheme != null then scheme else svc.upstreamScheme or "http";
            in {
              service = svc.name;
              inherit targetHost address;
              port = svc.port;
              scheme = endpointScheme;
              url = "${endpointScheme}://${address}:${toString svc.port}";
            };
      in
        if require then
          requireValue
            "fleetix.serviceEndpoint: reverse proxy service `${serviceName}` is missing or has no resolvable target"
            endpoint
        else
          endpoint;
  };

  firewall = {
    lanExposedPorts = {
      topology,
      hostName,
    }:
      map (svc: svc.port) (
        filter (svc: svc.lanExposed or false)
          (services.reverseProxyServicesForHost {
            inherit topology hostName;
            includeVpnOnly = false;
          })
      );
  };

  adapters.infernix = {
    mkFleetNodes = {
      topology,
      nodes,
      addressPolicy ? [ "lan" "direct-link" "wg-home" ],
      defaultModelPort ? 8013,
      defaultNodePort ? 8020,
    }:
      mapAttrs (
        hostName: node:
          let
            policy = node.addressPolicy or addressPolicy;
            nodeAddress = node.address or null;
            address =
              if nodeAddress != null then
                nodeAddress
              else
                hosts.resolveHostAddress {
                  inherit topology hostName policy;
                };
            nodeModelPort = node.modelPort or null;
            modelPort =
              if nodeModelPort != null then nodeModelPort else defaultModelPort;
            nodeNodePort = node.nodePort or null;
            nodePort =
              if nodeNodePort != null then nodeNodePort else defaultNodePort;
          in
            recursiveUpdate node {
              inherit address modelPort nodePort;
            }
            // optionalAttrs (hasAttr "addressPolicy" node) {
              addressPolicy = node.addressPolicy;
            }
      ) nodes;
  };

  # Compatibility aliases for existing consumers.
  resolveHostAddress = hosts.resolveHostAddress;
  serviceEndpoint = services.serviceEndpoint;
  reverseProxyServicesForHost = services.reverseProxyServicesForHost;
  lanExposedPorts = firewall.lanExposedPorts;

  # Derive a link's CIDR
  linkCidr = link: link.subnet;

  # Derive the server binding from a link
  linkServer = link: hosts:
    lib.head (
      filterAttrs (_: host:
        (host.links.${link.name} or {}).role or "" == "server"
      ) hosts
    );

  # Derive server address
  linkServerAddress = link: hosts:
    let
      server = linkServer link hosts;
    in
    server.value.links.${link.name}.address;

  # Derive listen address for a host on a link
  listenAddress = hostName: link: hosts:
    let
      host = hosts.${hostName};
      binding = host.links.${link.name};
      prefixLen = lib.head (splitString "/" link.subnet ++ ["24"]);
    in
    "${binding.address}/${prefixLen}";

  # Derive the full peers list for the server side
  linkPeers = linkName: hosts:
    let
      serverHost = lib.head (
        attrNames (filterAttrs (_: host:
          (host.links.${linkName} or {}).role or "" == "server"
        ) hosts)
      );
    in
    mapAttrsToList (name: host:
      let b = host.links.${linkName}; in {
        inherit name;
        publicKey = b.publicKey or "";
        allowedIPs = ["${b.address}/32"];
        inherit (b) address;
      }
    ) (builtins.removeAttrs hosts [serverHost]);
}
