{ lib }:
let
  inherit (builtins) attrValues attrNames;
  inherit (lib)
    filterAttrs
    hasSuffix
    mapAttrsToList
    splitString
    ;
in
rec {
  # Import a fleetix topology sidecar (.nix file generated by pklx eval).
  fromPkl = builtins.import;

  # Derive a link's CIDR
  linkCidr = link: link.subnet;

  # Derive the server binding from a link
  linkServer = link: hosts:
    lib.head (
      filterAttrs (_: host:
        (host.links.${link.name} or {}).role or "" == "server"
      ) hosts
    );

  # Derive server address
  linkServerAddress = link: hosts:
    let
      server = linkServer link hosts;
    in
    server.value.links.${link.name}.address;

  # Derive listen address for a host on a link
  listenAddress = hostName: link: hosts:
    let
      host = hosts.${hostName};
      binding = host.links.${link.name};
      prefixLen = lib.head (splitString "/" link.subnet ++ ["24"]);
    in
    "${binding.address}/${prefixLen}";

  # Derive the full peers list for the server side
  linkPeers = linkName: hosts:
    let
      serverHost = lib.head (
        attrNames (filterAttrs (_: host:
          (host.links.${linkName} or {}).role or "" == "server"
        ) hosts)
      );
    in
    mapAttrsToList (name: host:
      let b = host.links.${linkName}; in {
        inherit name;
        publicKey = b.publicKey or "";
        allowedIPs = ["${b.address}/32"];
        inherit (b) address;
      }
    ) (builtins.removeAttrs hosts [serverHost]);
}
